ACCESS_TOKEN: "USERIBM3S8OHEFTBLSG29JV1R2QOTNGRCV7IGI4R76K597MFIMVUJ9JR58LO8K86"
User_Agent: "AlfaHRService (alfa-hr-service@alfabank.by)"
API_URL: "https://api.hh.ru/resumes"
HOST: "rabota.by"
AREA: 16
