AUTHORIZATION_CODE: "MML66LDKRB03H7RRB4ENVO63CUP55NJPTFDVJ79881C5ACP6L79QH9DCV1IDP972"
Redirect_Uri: https://www.alfabank.by
User_Agent: "AlfaHRService (alfa-hr-service@alfabank.by)"
Client_Id: "PC1JCC77M8707UGQ4NPQK31P7CT4T8MK2HL61QABANE9J7POHS1GDNTC78SRJMCB"
Client_Secret: "PJCS60M220HSBI0H1TKFRCS7PVOCD2QF69AKROHM2LVIRPHOFGOV06NBHPVN2H4U"
App_Access_Token: "APPLS8AOGPI03E8OK9PKUABDT255LDGVSVQPLORCB4DC4313L3SUVQ9G98MB8J9F"
TOKEN_URL: "https://api.hh.ru/token"